### PR TITLE
Updated the MkDocs config from the deprecated format

### PR DESCRIPTION
**Pull request by d0ugal**

### CODE REVIEW

**Comment by avelino** [comment]
New syntax run in version `0.9`?
https://github.com/opps/opps/blob/master/requirements_dev.txt#L9

**Comment by d0ugal** [comment]
@avelino ah, no. I didn't notice you were on such an old version :) It requires 0.13+, the latest is 0.14

**Comment by d0ugal** [comment]
I can test it works well with the latest version and update that later.

**Comment by avelino** [comment]
for I accept your PR needs to update the install file `requirements_dev.txt#L9`

**Comment by d0ugal** [comment]
Updated.

**Pull request merged**
