### PR TITLE
Validation: Prevent duplicated containerbox

### PR DESCRIPTION
**Pull request by henriquechehad**
Issue: https://github.com/opps/opps/issues/474

### CODE REVIEW

**Comment by avelino** [comment]
hey man, build fail, check pep8 pls

**Comment by henriquechehad** [comment]
Thank you! I will check

**Comment by henriquechehad** [comment]
@avelino I commited the pep8 fix, but now happened this error:

error: Download error for https://pypi.python.org/packages/source/c/coverage/coverage-3.7.1.tar.gz#md5=c47b36ceb17eaff3ecfab3bcd347d0df: [Errno 110] Connection timed out

**Comment by lerrua** [comment]
@avelino @henriquechehad the build is okay now.

**Pull request merged**
